#!/usr/bin/env bash
set -e

if [ -z "$srcdir" ]
then
  srcdir=$(dirname "$0")
fi

entrypoints=$(grep EGL_ENTRYPOINT "$srcdir"/main/eglentrypoint.h)
sorted=$(LANG=C sort <<< "$entrypoints")
test "$entrypoints" = "$sorted"
